import { defineConfig } from 'astro/config';
import mdx from '@astrojs/mdx';
import sitemap from '@astrojs/sitemap';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';
import type { Plugin } from 'vite';
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { getNotePagePaths } from './src/data/notes';

// The notes under /notes/ are generated by wanshi into public/, so Astro never
// sees them as routes and the sitemap integration cannot discover them. Feed
// them in explicitly, read from the metadata index wanshi writes.
const site = 'https://pvomelveny.com';
const notePages = getNotePagePaths().map((path) => new URL(path, site).href);

/**
 * Dev-server URL resolution for the notes.
 *
 * Astro's dev server serves `public/` by exact path only — it does not resolve
 * directory indexes or try an `.html` extension. wanshi links its pages both
 * ways (`/notes/algebra/` for a directory index, `/notes/welcome` for a note,
 * since `pretty-urls` is on), so without this every note link 404s under
 * `npm run dev`. The preview server and production both resolve these already.
 *
 * This mirrors the CloudFront Function documented in the README — the same
 * rewrite, expressed for the dev server. Keep the two in step: a change to how
 * wanshi URLs are shaped needs updating in both places.
 *
 * Scoped to /notes/ so Astro's own routing is untouched, and only rewrites when
 * the target file actually exists, so a genuine typo still surfaces as a 404
 * rather than being masked.
 */
function notesDevUrls(): Plugin {
  const publicDir = join(process.cwd(), 'public');

  return {
    name: 'notes-dev-urls',
    apply: 'serve',
    configureServer(server) {
      server.middlewares.use((req, _res, next) => {
        const url = req.url;
        if (!url) return next();

        // Split off query/hash before touching the path.
        const split = url.search(/[?#]/);
        const path = split === -1 ? url : url.slice(0, split);
        const suffix = split === -1 ? '' : url.slice(split);

        if (path !== '/notes' && !path.startsWith('/notes/')) return next();

        let candidate: string | null = null;
        if (path === '/notes') {
          candidate = '/notes/index.html';
        } else if (path.endsWith('/')) {
          candidate = `${path}index.html`;
        } else {
          const last = path.slice(path.lastIndexOf('/') + 1);
          if (!last.includes('.')) candidate = `${path}.html`;
        }

        if (candidate && existsSync(join(publicDir, candidate))) {
          req.url = candidate + suffix;
        }

        next();
      });
    },
  };
}

export default defineConfig({
  // Canonical origin used for absolute URLs (sitemap, OpenGraph meta, etc.).
  // Update if the deployed domain ever changes.
  site,
  integrations: [mdx(), sitemap({ customPages: notePages })],
  markdown: {
    remarkPlugins: [remarkMath],
    rehypePlugins: [rehypeKatex],
  },
  vite: {
    plugins: [notesDevUrls()],
  },
});
