#import "/_lib/wanshi.typ": *

#show: wanshi

// Generated by `wanshi refs sync`. Edits are overwritten — notes about
// this work belong in an ordinary note that links here. Delete this
// comment to take the file over by hand.
#metadata((
  "title": "O'Donnell 2021 — Analysis of Boolean Functions",
  "taxon": "reference",
  "date": "2021",
  "author": "Ryan O'Donnell",
  "citekey": "odonnell2021",
  "type": "report",
  "doi": "10.48550/arXiv.2105.10386",
  "url": "http://arxiv.org/abs/2105.10386",
  "parent": "refs/index",
))

Ryan O'Donnell. _Analysis of Boolean Functions_. Report, 2021.

#external("https://arxiv.org/abs/2105.10386", "arXiv:2105.10386")
