#import "/_lib/wanshi.typ": *

#show: wanshi

#metadata((
  "title": "About these notes",
  "taxon": "note",
  "date": "2026-08-17",
  "description": "What this section is and how it is organized.",
))

These are working notes, not finished writing. Some are worked out carefully,
others are a paragraph I wanted to get out of my head. They are public mostly as
a way of making myself write things up somewhat sensibly.

Notes are organized as a forest rather than a feed: each one lives under the
topic it belongs to, and links between them are two-way — every note lists the
others that point at it. If the organization looks a little chaotic, that is
because it grows from whatever I am working on rather than from a plan.

Press `"/"` on any page to search. Matching is by word prefix and covers the
body text, so a phrase you half-remember is usually enough.

For who I am and what I work on, see the #external("/about", [main about page]).
For everything else, my contact details are in the footer.

The site is generated by #external("https://github.com/pvomelveny/wanshi", [wanshi]), a Typst-only static site generator I maintain for my own use. It is a
fork of #external("https://github.com/kodama-community/kodama", [kodama]), which
is the one to look at if you want a tool of this kind: it is properly
maintained, has a community around it, and takes Markdown as well as Typst. My
fork drops Markdown, replaces the visual design, and has drifted toward whatever
suited these notes — a different set of choices rather than a better one. Both
owe their arrangement to Jon Sterling's
#external("https://www.forester-notes.org/", [Forester]), which is where the
forest idea comes from.

