/**
 * Generates the site chrome that wanshi injects into every notes page.
 *
 * wanshi renders complete, standalone HTML documents — it cannot delegate to an
 * Astro layout. To make `/notes/**` read as part of this site rather than a
 * neighbour of it, wanshi reads two optional files from its project root and
 * splices them into `<body>`:
 *
 *   import-header.html  → very top of <body>, above wanshi's breadcrumb
 *   import-footer.html  → very end of <body>, below the content grid
 *   import-meta.html    → appended to <head>
 *
 * Both are static HTML, so the nav and footer would normally have to be
 * hand-copied — duplicating the name, email, and links that `src/data/site.ts`
 * exists to own. This script generates them from `site.ts` instead, keeping
 * that file the single source of truth. It runs before every `dev` and `build`
 * (see package.json), so the two halves of the site cannot drift apart.
 *
 * Markup mirrors `src/components/Nav.astro` and `src/components/Footer.astro`.
 * The classes are `site-` prefixed because wanshi already uses `.nav`, `.header`
 * and `.logo` for its own breadcrumb; the matching CSS lives in
 * `notes/import-style.html`.
 *
 * Run directly with `node scripts/gen-wanshi-chrome.ts` (Node >= 22.18 strips
 * the types natively — no build step, no extra dependency).
 */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { site } from "../src/data/site.ts";

const projectRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const wanshiRoot = join(projectRoot, "notes");

/** Escape a string for use as HTML text content or a double-quoted attribute. */
function esc(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

/** Banner warning editors off the generated files. */
const banner =
  "<!-- Generated by scripts/gen-wanshi-chrome.ts from src/data/site.ts.\n" +
  "     Do not edit by hand — `npm run dev` and `npm run build` overwrite it.\n" +
  "     Change the nav/footer in src/data/site.ts or that script instead. -->";

/**
 * Top-level nav links. Mirrors the `links` array in Nav.astro, with `notes`
 * marked active since every page carrying this header lives under /notes/.
 *
 * The notes href keeps its trailing slash: wanshi publishes the forest root as
 * `/notes/index.html`, which a directory URL resolves to on any static host.
 */
const navLinks = [
  { href: "/about", label: "about", external: false, active: false },
  { href: "/research", label: "research", external: false, active: false },
  { href: "/teaching", label: "teaching", external: false, active: false },
  { href: "/notes/", label: "notes", external: false, active: true },
  { href: site.cvUrl, label: "cv", external: true, active: false },
];

const navLinkHtml = navLinks
  .map(({ href, label, external, active }) => {
    const attrs = [`href="${esc(href)}"`];
    if (active) attrs.push('class="active"');
    if (external) attrs.push('target="_blank"', 'rel="noopener"');
    return `    <a ${attrs.join(" ")}>${esc(label)}</a>`;
  })
  .join("\n");

const header = `${banner}
<nav class="site-nav">
  <a href="/" class="site-nav-name">${esc(site.firstName)} <span>${esc(site.lastName)}</span></a>
  <div class="site-nav-links">
${navLinkHtml}
  </div>
</nav>
`;

const footer = `${banner}
<footer class="site-footer">
  <span class="site-footer-name">${esc(site.fullName)}</span>
  <div class="site-footer-links">
    <a href="mailto:${esc(site.email)}">email</a>
    <a href="${esc(site.github)}" target="_blank" rel="noopener noreferrer">github</a>
    <a href="${esc(site.scholar)}" target="_blank" rel="noopener noreferrer">google scholar</a>
  </div>
</footer>
`;

/**
 * Head tags, mirroring the equivalents in BaseLayout.astro.
 *
 * wanshi unconditionally links `assets/favicon.ico` — a symlink to
 * public/favicon.ico, so the .ico it publishes is already this site's. This
 * adds the SVG that modern browsers prefer, matching what the Astro pages
 * serve. Neither link declares `sizes`, so the browser chooses on type alone
 * rather than by declaration order.
 *
 * RSS autodiscovery points at the site's single feed at /rss.xml, which Astro
 * builds from wanshi.json. wanshi's own feed is off (see [publish] in
 * Wanshi.toml).
 */
const meta = `${banner}
<link rel="icon" type="image/svg+xml" href="/favicon.svg" />
<link
  rel="alternate"
  type="application/rss+xml"
  title="${esc(site.rssName)}"
  href="/rss.xml"
/>
`;

const outputs: Array<[string, string]> = [
  ["import-header.html", header],
  ["import-footer.html", footer],
  ["import-meta.html", meta],
];

for (const [name, contents] of outputs) {
  writeFileSync(join(wanshiRoot, name), contents, "utf8");
}

console.log(
  `wanshi chrome: wrote ${outputs.map(([name]) => `notes/${name}`).join(", ")}`,
);
